# Generated by Django 5.2.6 on 2025-09-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=50)),
                ('slug', models.TextField()),
                ('time_stamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
