# Generated by Django 5.2.6 on 2025-09-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_time_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
